# Copyright Takatoshi Kondo 2024
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

# An antora playbook used for local development
# The playbook includes async_mqtt as its only component

site:
  title: async_mqtt
  url: https://antora.cppalliance.org/develop/lib/doc
  start_page: async_mqtt::index.adoc
  robots: allow
  keys:
    repo_url: 'https://github.com/redboltz/async_mqtt'

content:
  sources:
    - url: ..
      start_path: doc
      edit_url: 'https://github.com/redboltz/async_mqtt/edit/{refname}/{path}'

ui:
  bundle:
    url: https://github.com/boostorg/website-v2-docs/releases/download/ui-master/ui-bundle.zip
    snapshot: true

antora:
  extensions:
    - require: '@antora/lunr-extension' # https://gitlab.com/antora/antora-lunr-extension
      index_latest_only: true
    - require: '@cppalliance/antora-cpp-tagfiles-extension'
      cpp-tagfiles:
        using-namespaces:
          - 'boost::'
    - require: '@cppalliance/antora-cpp-reference-extension'
      dependencies:
        - name: 'boost'
          repo: 'https://github.com/boostorg/boost.git'
          tag: 'develop'
          variable: 'BOOST_SRC_DIR'
          system-env: 'BOOST_SRC_DIR'

asciidoc:
  attributes:
    # Enable pagination
    page-pagination: ''
  extensions:
    - '@cppalliance/asciidoctor-boost-links'
    - '@asciidoctor/tabs'
